export const bgThemeColor = '#0955fd'
export const lineThemeColorLight = '#F8EFEF'
export const lineThemeColorDark = '#28282c'
export const borderDeactive = '#e5e7eb'
export const darkBtnDeactive = '#34373c'
export const darkBtnActive = '#4b9e5f'